---
- name: Add FTD CDO inventory
  hosts: localhost
  tasks:
    - name: Add FTD to CDO and cdFMC
      cisco.cdo.add_ftd:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
        region: 'us'
        add_ftd:
          onboard_method: 'ltp'
          serial: 'JADXXXXXXXX'
          access_control_policy: 'Default Access Control Policy'
          name: 'ElPaso'
          license:
            - BASE
            - THREAT
            - URLFilter
            - MALWARE
            - PLUS
      register: added_device
    - name: Print results
      ansible.builtin.debug:
        msg:
          "{{ added_device }}"
