---
- name: Add IOS Device to CDO inventory
  hosts: localhost
  tasks:
    - name: Add IOS Device to CDO
      cisco.cdo.add_asa_ios:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
        region: 'us'
        add_asa_ios:
          sdc: 'CDO_cisco_aahackne-SDC-1'
          name: 'Austin-CSR-1000v'
          ipv4: '172.30.4.250'
          port: 22
          device_type: 'ios'
          username: 'myuser'
          password: 'abc123'
          ignore_cert: true
      register: added_device

    - name: Print results
      ansible.builtin.debug:
        msg:
          "{{ added_device }}"
