---
- name: Delete IOS Device from CDO inventory
  hosts: localhost
  tasks:
    - name: Delete IOS Device from CDO inventory
      cisco.cdo.delete:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
        region: 'us'
        delete:
          name: 'Austin'
          device_type: 'asa'
